name: notifyu-ci

on:
  pull_request:
    branches:
      - develop

jobs:
  tests:
    runs-on: ubuntu-22.04

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: check environment variable
        run: echo $JWT_SECRET
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

      - name: install dependencies
        run: npm install

      - name: run tests
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
